language: node_js
node_js:
 - "stable"
before_install:
 - export CXX="g++-4.8" CC="gcc-4.8"
after_failure:
 - cat ./mysql-local/dbSqlCmd.out
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - mysql-client
    - mysql-server
sudo: false
